package euclr.tm.spark.ml.util

object StopWords {
    val stopWords =
        s"""
           |a
           |aan
           |aber
           |about
           |above
           |across
           |adesso
           |af
           |after
           |afterwards
           |again
           |against
           |ai
           |al
           |alguna
           |algunas
           |alguno
           |algunos
           |algún
           |all
           |alla
           |allo
           |allora
           |almost
           |alone
           |along
           |alors
           |already
           |als
           |also
           |although
           |altre
           |altri
           |altro
           |always
           |am
           |ambos
           |among
           |amongst
           |amoungst
           |amount
           |ampleamos
           |an
           |anche
           |ancora
           |and
           |another
           |ante
           |antes
           |any
           |anyhow
           |anyone
           |anything
           |anyway
           |anywhere
           |aquel
           |aquellas
           |aquellos
           |aqui
           |are
           |around
           |arriba
           |as
           |at
           |atras
           |au
           |auch
           |aucuns
           |auf
           |aus
           |aussi
           |autre
           |avant
           |avec
           |avere
           |aveva
           |avevano
           |avoir
           |back
           |bajo
           |bastante
           |be
           |became
           |because
           |become
           |becomes
           |becoming
           |been
           |before
           |beforehand
           |behind
           |bei
           |being
           |below
           |ben
           |beside
           |besides
           |between
           |beyond
           |bien
           |bij
           |bill
           |bin
           |bis
           |bist
           |bon
           |both
           |bottom
           |buono
           |but
           |by
           |cada
           |call
           |can
           |cannot
           |cant
           |car
           |ce
           |cela
           |ces
           |ceux
           |chaque
           |che
           |chi
           |ci
           |cierta
           |ciertas
           |cierto
           |ciertos
           |cinque
           |co
           |comme
           |comment
           |como
           |comprare
           |computer
           |con
           |consecutivi
           |consecutivo
           |conseguimos
           |conseguir
           |consigo
           |consigue
           |consiguen
           |consigues
           |cosa
           |could
           |couldnt
           |cry
           |cual
           |cuando
           |cui
           |da
           |dadurch
           |daher
           |dan
           |dans
           |darum
           |das
           |dass
           |dat
           |daß
           |de
           |dedans
           |dehors
           |dein
           |deine
           |del
           |della
           |dello
           |dem
           |den
           |dentro
           |depuis
           |der
           |des
           |describe
           |desde
           |deshalb
           |dessen
           |detail
           |deve
           |devo
           |devrait
           |di
           |die
           |dies
           |dieser
           |dieses
           |dit
           |do
           |doch
           |doit
           |donc
           |donde
           |done
           |doppio
           |dort
           |dos
           |down
           |du
           |due
           |durch
           |during
           |début
           |e
           |each
           |ecco
           |een
           |eg
           |eight
           |ein
           |eine
           |einem
           |einen
           |einer
           |eines
           |either
           |el
           |eleven
           |ellas
           |elle
           |elles
           |ellos
           |else
           |elsewhere
           |empleais
           |emplean
           |emplear
           |empleas
           |empleo
           |empty
           |en
           |encima
           |encore
           |enough
           |entonces
           |entre
           |er
           |era
           |eramos
           |eran
           |eras
           |eres
           |es
           |essai
           |est
           |esta
           |estaba
           |estado
           |estais
           |estamos
           |estan
           |estoy
           |et
           |etc
           |eu
           |euer
           |eure
           |even
           |ever
           |every
           |everyone
           |everything
           |everywhere
           |except
           |fait
           |faites
           |fare
           |few
           |fifteen
           |fify
           |fill
           |fin
           |find
           |fine
           |fino
           |fire
           |first
           |five
           |fois
           |font
           |for
           |former
           |formerly
           |forty
           |found
           |four
           |fra
           |from
           |front
           |fue
           |fueron
           |fui
           |fuimos
           |full
           |further
           |für
           |gente
           |get
           |giu
           |give
           |go
           |gueno
           |ha
           |hace
           |haceis
           |hacemos
           |hacen
           |hacer
           |haces
           |had
           |hago
           |hai
           |hanno
           |has
           |hasnt
           |hatte
           |hatten
           |hattest
           |hattet
           |have
           |he
           |heb
           |hem
           |hence
           |her
           |here
           |hereafter
           |hereby
           |herein
           |hereupon
           |hers
           |herself
           |het
           |hier
           |hij
           |him
           |himself
           |hinter
           |his
           |ho
           |hoe
           |hors
           |how
           |however
           |hun
           |hundred
           |i
           |ich
           |ici
           |ie
           |if
           |ihr
           |ihre
           |ik
           |il
           |ils
           |im
           |in
           |inc
           |incluso
           |indeed
           |indietro
           |intenta
           |intentais
           |intentamos
           |intentan
           |intentar
           |intentas
           |intento
           |interest
           |into
           |invece
           |io
           |ir
           |is
           |ist
           |it
           |its
           |itself
           |ja
           |je
           |jede
           |jedem
           |jeden
           |jeder
           |jedes
           |jener
           |jenes
           |jetzt
           |juste
           |kan
           |kann
           |kannst
           |keep
           |können
           |könnt
           |la
           |largo
           |las
           |last
           |latter
           |latterly
           |lavoro
           |le
           |least
           |lei
           |les
           |less
           |leur
           |lo
           |loro
           |los
           |ltd
           |lui
           |lungo
           |là
           |ma
           |machen
           |made
           |maintenant
           |mais
           |many
           |may
           |me
           |meanwhile
           |meglio
           |mein
           |meine
           |men
           |mes
           |met
           |mientras
           |might
           |mij
           |mill
           |mine
           |mio
           |mit
           |modo
           |moins
           |molta
           |molti
           |molto
           |mon
           |more
           |moreover
           |most
           |mostly
           |mot
           |move
           |much
           |muchos
           |musst
           |must
           |muy
           |muß
           |mußt
           |my
           |myself
           |même
           |müssen
           |müßt
           |nach
           |nachdem
           |name
           |namely
           |nei
           |nein
           |neither
           |nella
           |never
           |nevertheless
           |next
           |ni
           |nicht
           |nine
           |no
           |nobody
           |nog
           |noi
           |nome
           |nommés
           |none
           |noone
           |nor
           |nos
           |nosotros
           |nostro
           |not
           |nothing
           |notre
           |nous
           |nove
           |now
           |nowhere
           |nu
           |nun
           |nuovi
           |nuovo
           |o
           |oder
           |of
           |off
           |often
           |oltre
           |on
           |once
           |one
           |only
           |ons
           |onto
           |ook
           |or
           |ora
           |other
           |others
           |otherwise
           |otro
           |otto
           |ou
           |our
           |ours
           |ourselves
           |out
           |over
           |own
           |où
           |par
           |para
           |parce
           |part
           |pas
           |peggio
           |per
           |perhaps
           |pero
           |persone
           |peu
           |peut
           |piu
           |please
           |plupart
           |poco
           |podeis
           |podemos
           |poder
           |podria
           |podriais
           |podriamos
           |podrian
           |podrias
           |por
           |porque
           |pour
           |pourquoi
           |primero
           |primo
           |promesso
           |puede
           |pueden
           |puedo
           |put
           |qua
           |quand
           |quarto
           |quasi
           |quattro
           |que
           |quel
           |quelle
           |quelles
           |quello
           |quels
           |questo
           |qui
           |quien
           |quindi
           |quinto
           |qué
           |rather
           |re
           |rispetto
           |sa
           |sabe
           |sabeis
           |sabemos
           |saben
           |saber
           |sabes
           |same
           |sans
           |sara
           |secondo
           |see
           |seem
           |seemed
           |seeming
           |seems
           |sei
           |seid
           |sein
           |seine
           |sembra
           |sembrava
           |senza
           |ser
           |serious
           |ses
           |sette
           |seulement
           |several
           |she
           |should
           |show
           |si
           |sia
           |siamo
           |sich
           |side
           |sie
           |sien
           |siendo
           |siete
           |sin
           |since
           |sincere
           |sind
           |six
           |sixty
           |so
           |sobre
           |sois
           |solamente
           |soll
           |sollen
           |sollst
           |sollt
           |solo
           |some
           |somehow
           |someone
           |something
           |sometime
           |sometimes
           |somewhere
           |somos
           |son
           |sono
           |sonst
           |sont
           |sopra
           |soprattutto
           |sotto
           |sous
           |soweit
           |sowie
           |soy
           |soyez
           |stati
           |stato
           |stesso
           |still
           |su
           |subito
           |such
           |sujet
           |sul
           |sulla
           |sur
           |sus
           |system
           |ta
           |take
           |también
           |tandis
           |tanto
           |te
           |tellement
           |tels
           |tempo
           |ten
           |teneis
           |tenemos
           |tener
           |tengo
           |terzo
           |tes
           |than
           |that
           |the
           |their
           |them
           |themselves
           |then
           |thence
           |there
           |thereafter
           |thereby
           |therefore
           |therein
           |thereupon
           |these
           |they
           |thick
           |thin
           |third
           |this
           |those
           |though
           |three
           |through
           |throughout
           |thru
           |thus
           |tiempo
           |tiene
           |tienen
           |to
           |todo
           |together
           |ton
           |too
           |top
           |tot
           |tous
           |tout
           |toward
           |towards
           |tra
           |trabaja
           |trabajais
           |trabajamos
           |trabajan
           |trabajar
           |trabajas
           |trabajo
           |tras
           |tre
           |triplo
           |trop
           |très
           |tu
           |tuyo
           |twelve
           |twenty
           |two
           |uit
           |ultimo
           |un
           |una
           |unas
           |und
           |under
           |uno
           |unos
           |unser
           |unsere
           |unter
           |until
           |up
           |upon
           |us
           |usa
           |usais
           |usamos
           |usan
           |usar
           |usas
           |uso
           |va
           |vai
           |vais
           |valor
           |vamos
           |van
           |vaya
           |verdad
           |verdadera
           |verdadero
           |very
           |via
           |voi
           |voient
           |volte
           |vom
           |von
           |vont
           |vor
           |vosotras
           |vosotros
           |vostro
           |votre
           |vous
           |voy
           |vu
           |wann
           |warum
           |was
           |wat
           |we
           |weiter
           |weitere
           |wel
           |well
           |wenn
           |wer
           |werde
           |werden
           |werdet
           |were
           |weshalb
           |what
           |whatever
           |when
           |whence
           |whenever
           |where
           |whereafter
           |whereas
           |whereby
           |wherein
           |whereupon
           |wherever
           |whether
           |which
           |while
           |whither
           |who
           |whoever
           |whole
           |whom
           |whose
           |why
           |wie
           |wieder
           |wieso
           |wij
           |will
           |wir
           |wird
           |wirst
           |with
           |within
           |without
           |wo
           |woher
           |wohin
           |would
           |yet
           |yo
           |you
           |your
           |yours
           |yourself
           |yourselves
           |zal
           |ze
           |zei
           |zij
           |zo
           |zou
           |zu
           |zum
           |zur
           |ça
           |étaient
           |état
           |étions
           |été
           |être
           |über
           |""".stripMargin.split("\n")
}
